CREATE PROCEDURE SMY.PROC_FIX_OU_DEP_DLY_SMY(IN ACCOUNTING_DATE DATE)
-------------------------------------------------------------------------------
-- (C) Copyright ZJRCU and IBM <date>
--
-- File name:           SMY.PROC_OU_DEP_DLY_SMY.sql
-- Procedure name: 			SMYPROC_FIX_OU_DEP_DLY_SMY
-- Source Table:				SMY.OU_DEP_DLY_SMY

-- Target Table: 				SMY.OU_DEP_DLY_SMY 
-- Project     :        
-- NOTES       :        更改个人、单位通知存款年累计值。
-- Purpose     :            
-- PROCESS METHOD      :  INSERT ONLY EACH DAY
--=============================================================================
-- Creation Date:       2010.07.26
-- Origin Author:       
--
-- Version: %1.0%
--
-- Modification History
-- --------------------
--
-- Date         ByPerson        Description
-- ----------   --------------  -----------------------------------------------
-- 2010-07-26   ZHANGYONG     Create SP File
-------------------------------------------------------------------------------
LANGUAGE SQL
BEGIN

/*声明异常处理使用变量*/
		DECLARE SQLCODE, SMY_SQLCODE INT DEFAULT 0;            --SQLCODE
		DECLARE SMY_STEPNUM INT DEFAULT 1;                     --过程内部位置标记
		DECLARE SMY_STEPDESC VARCHAR(100) DEFAULT '';          --过程内部位置描述
		DECLARE SMY_DATE DATE;        --临时日期变量
		DECLARE SMY_RCOUNT INT;       --DML语句作用记录数
		DECLARE SMY_PROCNM VARCHAR(100);
		DECLARE LST_DAY DATE;
    SET SMY_DATE=ACCOUNTING_DATE;
    SET LST_DAY=SMY_DATE - 1 DAYS;

IF YEAR(SMY_DATE)=2010 THEN 

DECLARE GLOBAL TEMPORARY TABLE TMP as(
		SELECT T1.ACG_OU_IP_ID ACG_OU_IP_ID,
		T1.DEP_ACG_SBJ_ID DEP_ACG_SBJ_ID,
		T1.PD_GRP_CD PD_GRP_CD,
		T1.PD_SUB_CD PD_SUB_CD,
		T1.DEP_TM_TP_ID DEP_TM_TP_ID,
		T1.TM_MAT_SEG_ID TM_MAT_SEG_ID,
		T1.AC_CHRCTR_TP_ID AC_CHRCTR_TP_ID,
		T1.ENT_IDV_IND ENT_IDV_IND,
		T1.CCY CCY, 
		T2.YTD_ACML_BAL_AMT YTD_ACML_BAL_AMT,
		T1.BAL_AMT BAL_AMT,
		VALUE(T2.YTD_ACML_BAL_AMT,0)+VALUE(T1.BAL_AMT,0) YTD_BAL_AMT
		FROM SMY.OU_DEP_DLY_SMY T1
		LEFT JOIN SMY.OU_DEP_DLY_SMY T2  
		ON T1.ACG_OU_IP_ID      = T2.ACG_OU_IP_ID   
		AND T1.DEP_ACG_SBJ_ID   = T2.DEP_ACG_SBJ_ID 
		AND T1.PD_GRP_CD        = T2.PD_GRP_CD      
		AND T1.PD_SUB_CD        = T2.PD_SUB_CD      
		AND T1.DEP_TM_TP_ID     = T2.DEP_TM_TP_ID   
		AND T1.DEP_TM_TP_ID     = T2.TM_MAT_SEG_ID  
		AND T1.AC_CHRCTR_TP_ID  = T2.AC_CHRCTR_TP_ID
		AND T1.ENT_IDV_IND      = T2.ENT_IDV_IND    
		AND T1.CCY              = T2.CCY     AND   T2.ACG_DT=(date('2010-04-01') - 1 days) AND  T2.NEW_ACG_SBJ_ID IN ('20020102','20040106') 
		WHERE T1.NEW_ACG_SBJ_ID IN ('20020102','20040106')
		AND T1.ACG_DT=date('2010-04-01')
) DEFINITION ONLY ON COMMIT PRESERVE ROWS NOT LOGGED WITH REPLACE  IN TS_USR_TMP32K;
 
INSERT INTO SESSION.TMP
	SELECT T1.ACG_OU_IP_ID ACG_OU_IP_ID,
	T1.DEP_ACG_SBJ_ID DEP_ACG_SBJ_ID,
	T1.PD_GRP_CD PD_GRP_CD,
	T1.PD_SUB_CD PD_SUB_CD,
	T1.DEP_TM_TP_ID DEP_TM_TP_ID,
	T1.TM_MAT_SEG_ID TM_MAT_SEG_ID,
	T1.AC_CHRCTR_TP_ID AC_CHRCTR_TP_ID,
	T1.ENT_IDV_IND ENT_IDV_IND,
	T1.CCY CCY,
	T2.YTD_ACML_BAL_AMT YTD_ACML_BAL_AMT,
	T1.BAL_AMT BAL_AMT,
	VALUE(T2.YTD_ACML_BAL_AMT,0)+VALUE(T1.BAL_AMT,0) YTD_BAL_AMT
	FROM SMY.OU_DEP_DLY_SMY T1
	LEFT JOIN SMY.OU_DEP_DLY_SMY T2  
	ON T1.ACG_OU_IP_ID      = T2.ACG_OU_IP_ID   
	AND T1.DEP_ACG_SBJ_ID   = T2.DEP_ACG_SBJ_ID 
	AND T1.PD_GRP_CD        = T2.PD_GRP_CD      
	AND T1.PD_SUB_CD        = T2.PD_SUB_CD      
	AND T1.DEP_TM_TP_ID     = T2.DEP_TM_TP_ID   
	AND T1.TM_MAT_SEG_ID     = T2.TM_MAT_SEG_ID  
	AND T1.AC_CHRCTR_TP_ID  = T2.AC_CHRCTR_TP_ID
	AND T1.ENT_IDV_IND      = T2.ENT_IDV_IND    
	AND T1.CCY              = T2.CCY     AND   T2.ACG_DT=(SMY_DATE - 1 DAYS) AND  T2.NEW_ACG_SBJ_ID IN ('20020102','20040106')
	WHERE T1.NEW_ACG_SBJ_ID IN ('20020102','20040106')
	AND T1.ACG_DT=SMY_DATE ; 
	
UPDATE SMY.OU_DEP_DLY_SMY T1 SET YTD_ACML_BAL_AMT=(
SELECT  YTD_BAL_AMT FROM SESSION.TMP T2 
WHERE T1.ACG_OU_IP_ID      = T2.ACG_OU_IP_ID   
AND T1.DEP_ACG_SBJ_ID   = T2.DEP_ACG_SBJ_ID 
AND T1.PD_GRP_CD        = T2.PD_GRP_CD      
AND T1.PD_SUB_CD        = T2.PD_SUB_CD      
AND T1.DEP_TM_TP_ID     = T2.DEP_TM_TP_ID   
AND T1.TM_MAT_SEG_ID     = T2.TM_MAT_SEG_ID  
AND T1.AC_CHRCTR_TP_ID  = T2.AC_CHRCTR_TP_ID
AND T1.ENT_IDV_IND      = T2.ENT_IDV_IND    
AND T1.CCY              = T2.CCY  
)
WHERE ACG_DT=SMY_DATE AND T1.NEW_ACG_SBJ_ID IN ('20020102','20040106');
END IF;

END
@